### ISSUE TITLE
Agrupar y ordenar el documento

### ISSUE THREAD

**Issue by DavidFontalba** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-Javierfernandezrubio#1]
En el documento, hay muchas clases que se describen en diversos sitios, ( básicamente, hay varios .contendor {...}. .contenedor h2 {...} ), agrúpalos para que se quede más legible y entendible.

https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-Javierfernandezrubio/blob/f144e2438e02a440c55adebaf7adcbb74758bc8c/categorias.css#L63

**Comment by Javierfernandezrubio** [comment]
Vale bro, ahora lo arreglo!
